#!/bin/ksh

echo " "
echo "Ingresa el mensaje nuevo: "; read mensaje
echo " "
echo $mensaje
read 

git add . 
git commit -m "$mensaje" 
git pull origin master
git push origin master

echo " "
echo "LISTO!"
echo " "

