#!/bin/ksh

echo " "
echo -c "Ingresa el mensaje nuevo: "; read mensaje
echo $mensaje

git add . 
git commit -m $mensaje 
git pull origin master
git push origin master

echo " "
echo "LISTO!"
echo " "

