#!/bin/ksh

echo " "
echo "Ingresa el mensaje nuevo: "; read -c mensaje
echo " "
echo $mensaje
pause

git add . 
git commit -m '$mensaje' 
git pull origin master
git push origin master

echo " "
echo "LISTO!"
echo " "

